INSERT INTO CATEGORIA (nombre, descripcion) VALUES
('Cómics', 'Eventos relacionados con cómics y novelas gráficas'),
('Manga y Anime', 'Actividades dedicadas al manga y anime'),
('Superhéroes', 'Convenciones sobre personajes de cómics de superhéroes'),
('Ciencia Ficción', 'Eventos centrados en la ciencia ficción y futurismo'),
('Fantasía', 'Convenciones sobre mundos fantásticos y magia'),
('Videojuegos', 'Competiciones y exposiciones de videojuegos'),
('Juegos de Mesa', 'Torneos y demostraciones de juegos de mesa'),
('Rol en Vivo', 'Juegos de rol en vivo y recreaciones'),
('Cultura Geek', 'Eventos dedicados a la cultura geek y friki'),
('Películas y Series', 'Actividades sobre cine y televisión geek'),
('Cosplay', 'Concursos y exhibiciones de cosplay'),
('Ilustración y Dibujo', 'Talleres y exposiciones de ilustración'),
('Guionismo', 'Conferencias sobre guionismo en cómics y películas'),
('Efectos Especiales', 'Charlas sobre efectos especiales en cine y videojuegos'),
('Realidad Virtual', 'Experiencias y demostraciones de realidad virtual'),
('Inteligencia Artificial en Juegos', 'Conferencias sobre IA en videojuegos'),
('Tecnología en el Entretenimiento', 'Innovaciones tecnológicas en el entretenimiento'),
('Figuras y Coleccionismo', 'Exposiciones y ventas de figuras coleccionables'),
('Cultura Retro', 'Eventos sobre videojuegos y películas retro'),
('Industrias Creativas', 'Charlas sobre la industria del entretenimiento'),
('Cine Independiente', 'Proyecciones de cine independiente geek'),
('E-Sports', 'Competiciones de deportes electrónicos'),
('Merchandising', 'Feria de productos geek y frikis'),
('Doblatón', 'Charlas y encuentros con actores de doblaje'),
('Juegos de Cartas', 'Torneos de juegos de cartas coleccionables'),
('Realidad Aumentada', 'Aplicaciones y experiencias de realidad aumentada'),
('Fandoms y Comunidades', 'Encuentros de fans de diversas franquicias'),
('Streaming y Creadores de Contenido', 'Charlas con influencers y streamers'),
('Escritura Creativa', 'Talleres de escritura para historias geek');

-- Insertar 30 eventos relacionados con la convención
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES
('Torneo de Smash Bros', 'Competencia de Super Smash Bros.', 'Sala de Videojuegos', '2025-06-10', '2025-06-10', 6),
('Concurso de Cosplay', 'Desfile y concurso de cosplay', 'Escenario Principal', '2025-07-15', '2025-07-15', 11),
('Panel de Doblaje', 'Encuentro con actores de doblaje famosos', 'Sala 3', '2025-05-20', '2025-05-20', 25),
('Charla sobre Guionismo', 'Conferencia sobre escritura de guiones para cómics', 'Auditorio', '2025-08-01', '2025-08-01', 13),
('Proyección de Película Geek', 'Estreno de una película de culto', 'Sala de Cine', '2025-04-05', '2025-04-05', 10),
('Exposición de Figuras Coleccionables', 'Muestra de figuras de colección', 'Pabellón de Exposiciones', '2025-09-12', '2025-09-12', 18),
('Concurso de Ilustración', 'Competencia de dibujo en vivo', 'Sala de Arte', '2025-10-10', '2025-10-10', 12),
('Torneo de Magic: The Gathering', 'Campeonato de cartas coleccionables', 'Zona de Juegos de Mesa', '2025-06-30', '2025-06-30', 26),
('Conferencia sobre IA en Videojuegos', 'Mesa redonda sobre inteligencia artificial', 'Sala de Tecnología', '2025-11-20', '2025-11-20', 16),
('Presentación de Cómic Independiente', 'Autores presentan sus cómics', 'Zona de Autores', '2025-08-15', '2025-08-15', 1),
('Panel de Cultura Retro', 'Charla sobre videojuegos y películas clásicas', 'Sala de Conferencias', '2025-09-01', '2025-09-01', 19);


-- Insertar 100 personas en la tabla PERSONA con nombres reales españoles
INSERT INTO PERSONA (nombre, apellido1, apellido2)
VALUES
('Alejandro', 'García', 'López'),
('María', 'Martínez', 'Pérez'),
('Carlos', 'Fernández', 'González'),
('Lucía', 'Rodríguez', 'Sánchez'),
('David', 'Gómez', 'Martín'),
('Laura', 'Hernández', 'Jiménez'),
('Javier', 'Díaz', 'Ruiz'),
('Ana', 'Moreno', 'Álvarez'),
('Sergio', 'Muñoz', 'Romero'),
('Marta', 'Alonso', 'Navarro'),
('Pablo', 'Gutiérrez', 'Torres'),
('Elena', 'Ramírez', 'Domínguez'),
('Raúl', 'Vázquez', 'Castro'),
('Claudia', 'Serrano', 'Gil'),
('Adrián', 'Molina', 'Ortiz'),
('Isabel', 'Rubio', 'Marín'),
('Fernando', 'Santos', 'Iglesias'),
('Patricia', 'Ortega', 'Sanz'),
('Iván', 'Castillo', 'Núñez'),
('Sara', 'Delgado', 'Lorenzo'),
('Alberto', 'Ramos', 'Hidalgo'),
('Cristina', 'Medina', 'Garrido'),
('Rubén', 'Vega', 'Cano'),
('Sofía', 'Cruz', 'Prieto'),
('Miguel', 'Flores', 'Méndez'),
('Paula', 'Herrera', 'Santiago'),
('Álvaro', 'Marquez', 'Trujillo'),
('Irene', 'Peña', 'Cabrera'),
('Hugo', 'Carmona', 'Fuentes'),
('Nuria', 'Blanco', 'Campos'),
('Manuel', 'López', 'Reyes'),
('Carmen', 'Martín', 'Aguilar'),
('Luis', 'Jiménez', 'Pascual'),
('Rocío', 'Ruiz', 'Santana'),
('Óscar', 'Navarro', 'Mora'),
('Silvia', 'Romero', 'Vicente'),
('Mario', 'Torres', 'Benítez'),
('Eva', 'Domínguez', 'Soler'),
('Andrés', 'Gil', 'Esteban'),
('Alicia', 'Castro', 'Parra'),
('Daniel', 'Ortiz', 'Rojas'),
('Beatriz', 'Marín', 'Saez'),
('Víctor', 'Iglesias', 'Montes'),
('Natalia', 'Sanz', 'Caballero'),
('Francisco', 'Núñez', 'León'),
('Clara', 'Lorenzo', 'Rivas'),
('Enrique', 'Hidalgo', 'Vargas'),
('Teresa', 'Garrido', 'Guerrero'),
('Guillermo', 'Cano', 'Paredes'),
('Julia', 'Prieto', 'Moya'),
('Ángel', 'Méndez', 'Manzano'),
('Lorena', 'Santiago', 'Soto'),
('Emilio', 'Trujillo', 'Suárez'),
('Verónica', 'Cabrera', 'Román'),
('Jaime', 'Fuentes', 'Pastor'),
('Sandra', 'Campos', 'Velasco'),
('Tomás', 'Reyes', 'Carrasco'),
('Noelia', 'Aguilar', 'Sierra'),
('Eduardo', 'Pascual', 'Segura'),
('Raquel', 'Santana', 'Lara'),
('Marcos', 'Mora', 'Arias'),
('Inés', 'Vicente', 'Vidal'),
('Alfonso', 'Benítez', 'Crespo'),
('Victoria', 'Soler', 'Gallardo'),
('Esteban', 'Esteban', 'Calvo'),
('Pilar', 'Parra', 'Ibáñez'),
('Diego', 'Rojas', 'Duran'),
('Ángela', 'Saez', 'Vera'),
('Jorge', 'Montes', 'Rubio'),
('Lidia', 'Caballero', 'Márquez'),
('Héctor', 'León', 'Peña'),
('Mónica', 'Rivas', 'Herrero'),
('Ignacio', 'Vargas', 'Luna'),
('Carolina', 'Guerrero', 'Aguado'),
('Samuel', 'Paredes', 'Casado'),
('Nerea', 'Moya', 'Menéndez'),
('Gabriel', 'Manzano', 'Vicens'),
('Rosa', 'Soto', 'Gallego'),
('Vicente', 'Suárez', 'Pérez'),
('Amparo', 'Román', 'Cortés'),
('Félix', 'Pastor', 'Delgado'),
('Ágata', 'Velasco', 'Mendoza'),
('Pedro', 'Carrasco', 'Santos'),
('Cristina', 'Sierra', 'Reina'),
('Juan', 'Segura', 'López'),
('Marina', 'Lara', 'Martínez'),
('Antonio', 'Arias', 'Gómez'),
('Elisa', 'Vidal', 'Hernández'),
('Ricardo', 'Crespo', 'Díaz'),
('Celia', 'Gallardo', 'Moreno'),
('Joaquín', 'Calvo', 'Muñoz'),
('Belén', 'Ibáñez', 'Ramos'),
('Paulina', 'Dominguez', 'Ferrer'),
('Mauro', 'Ezequiel', 'Lombardo'),
('Jude', 'Bellingham', 'Madrid'),
('Paco', 'Gonzalez', 'Cariñoso'),
('Cristiano', 'Ronaldo', 'Goat'),
('Kilian', 'Mbappe', 'Lottin'),
('Goku', 'Kakarot', 'SuperSaiyajin'),
('Roberto', 'Fernandez', 'Diaz');


-- Insertar 90 participantes en la tabla PARTICIPANTE
INSERT INTO PARTICIPANTE (id, email)
SELECT id, CONCAT(nombre, '.', apellido1, '@correo.com')
FROM PERSONA
WHERE id <= 90;

-- Insertar 10 artistas en la tabla ARTISTA
INSERT INTO ARTISTA (id, fotografia, obra_destacada)
SELECT id, CONCAT('foto_', id, '.jpg'), CONCAT('Obra destacada ', id)
FROM PERSONA
WHERE id > 90;

-- Insertar participaciones en la tabla PARTICIPA
INSERT INTO PARTICIPA (id_persona, id_evento, fecha) VALUES
(1, 1, '2025-06-10'),
(1, 2, '2025-07-15'),
(1, 3, '2025-05-20'),
(2, 1, '2025-06-10'),
(2, 4, '2025-08-01'),
(2, 5, '2025-04-05'),
(3, 6, '2025-09-12'),
(3, 7, '2025-10-10'),
(3, 8, '2025-06-30'),
(4, 9, '2025-11-20'),
(4, 10, '2025-08-15'),
(4, 1, '2025-06-10'),
(5, 2, '2025-07-15'),
(5, 3, '2025-05-20'),
(5, 4, '2025-08-01'),
(6, 5, '2025-04-05'),
(6, 6, '2025-09-12'),
(6, 7, '2025-10-10'),
(7, 8, '2025-06-30'),
(7, 9, '2025-11-20'),
(7, 10, '2025-08-15'),
(8, 1, '2025-06-10'),
(8, 2, '2025-07-15'),
(8, 3, '2025-05-20'),
(9, 4, '2025-08-01'),
(9, 5, '2025-04-05'),
(9, 6, '2025-09-12'),
(10, 7, '2025-10-10'),
(10, 8, '2025-06-30'),
(10, 9, '2025-11-20');



