-- 1. Insertar 200 Categorías
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Videojuegos', 'Categoría dedicada a los videojuegos, abarcando desde consolas retro hasta las últimas tendencias en gaming.');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Manga', 'Espacio para los amantes del manga, con obras clásicas y novedades del mercado japonés.');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Rol en Vivo', 'Actividades y eventos para los entusiastas del rol en vivo, con escenarios inmersivos y personajes únicos.');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cine', 'Categoría enfocada en el cine, desde películas clásicas hasta los últimos estrenos de Hollywood.');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Guionismo', 'Sección dedicada al arte de escribir guiones para cine, televisión y teatro.');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Merchandising', 'Explora productos exclusivos y coleccionables de tus franquicias favoritas.');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Anime', 'Un espacio para los fanáticos del anime, con series y películas icónicas.');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Superheroes', 'Categoría dedicada a los superhéroes, desde cómics hasta películas y series.');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Retro', 'Revive la nostalgia con contenido retro, desde videojuegos hasta cultura pop.');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fandom', 'Un lugar para celebrar y compartir la pasión por tus franquicias favoritas.');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Rol en Vivo', 'Rol en Vivo Categoria 12');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cultura Pop', 'Cultura Pop Categoria 13');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Videojuegos', 'Videojuegos Categoria 14');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Doblaje', 'Doblaje Categoria 15');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fandom', 'Fandom Categoria 16');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cine', 'Cine Categoria 17');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fandom', 'Fandom Categoria 18');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Superheroes', 'Superheroes Categoria 19');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Tecnologia', 'Tecnologia Categoria 20');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Realidad Virtual', 'Realidad Virtual Categoria 21');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Tecnologia', 'Tecnologia Categoria 22');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Manga', 'Manga Categoria 23');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fantasia', 'Fantasia Categoria 24');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('E-Sports', 'E-Sports Categoria 25');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('IA', 'IA Categoria 26');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fandom', 'Fandom Categoria 27');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Guionismo', 'Guionismo Categoria 28');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cosplay', 'Cosplay Categoria 29');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Merchandising', 'Merchandising Categoria 30');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Guionismo', 'Guionismo Categoria 31');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fantasia', 'Fantasia Categoria 32');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Rol en Vivo', 'Rol en Vivo Categoria 33');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Manga', 'Manga Categoria 34');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cine', 'Cine Categoria 35');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Coleccionismo', 'Coleccionismo Categoria 36');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Ilustracion', 'Ilustracion Categoria 37');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cultura Pop', 'Cultura Pop Categoria 38');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Juegos de Mesa', 'Juegos de Mesa Categoria 39');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fantasia', 'Fantasia Categoria 40');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Ciencia Ficcion', 'Ciencia Ficcion Categoria 41');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fandom', 'Fandom Categoria 42');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Coleccionismo', 'Coleccionismo Categoria 43');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fantasia', 'Fantasia Categoria 44');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Series', 'Series Categoria 45');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Realidad Virtual', 'Realidad Virtual Categoria 46');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Doblaje', 'Doblaje Categoria 47');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Coleccionismo', 'Coleccionismo Categoria 48');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Juegos de Mesa', 'Juegos de Mesa Categoria 49');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cultura Pop', 'Cultura Pop Categoria 50');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Manga', 'Manga Categoria 51');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Guionismo', 'Guionismo Categoria 52');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Ilustracion', 'Ilustracion Categoria 53');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Anime', 'Anime Categoria 54');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Retro', 'Retro Categoria 55');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Comics', 'Comics Categoria 56');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Ciencia Ficcion', 'Ciencia Ficcion Categoria 57');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Comics', 'Comics Categoria 58');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('IA', 'IA Categoria 59');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Anime', 'Anime Categoria 60');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Rol en Vivo', 'Rol en Vivo Categoria 61');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Tecnologia', 'Tecnologia Categoria 62');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Manga', 'Manga Categoria 63');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Rol en Vivo', 'Rol en Vivo Categoria 64');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('E-Sports', 'E-Sports Categoria 65');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Comics', 'Comics Categoria 66');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fantasia', 'Fantasia Categoria 67');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fantasia', 'Fantasia Categoria 68');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Realidad Virtual', 'Realidad Virtual Categoria 69');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fantasia', 'Fantasia Categoria 70');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Merchandising', 'Merchandising Categoria 71');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cultura Pop', 'Cultura Pop Categoria 72');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Videojuegos', 'Videojuegos Categoria 73');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Realidad Virtual', 'Realidad Virtual Categoria 74');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Comics', 'Comics Categoria 75');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cultura Pop', 'Cultura Pop Categoria 76');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('IA', 'IA Categoria 77');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Anime', 'Anime Categoria 78');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Tecnologia', 'Tecnologia Categoria 79');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Guionismo', 'Guionismo Categoria 80');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Juegos de Mesa', 'Juegos de Mesa Categoria 81');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Coleccionismo', 'Coleccionismo Categoria 82');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Realidad Virtual', 'Realidad Virtual Categoria 83');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cine', 'Cine Categoria 84');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Videojuegos', 'Videojuegos Categoria 85');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cultura Pop', 'Cultura Pop Categoria 86');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cosplay', 'Cosplay Categoria 87');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('IA', 'IA Categoria 88');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Doblaje', 'Doblaje Categoria 89');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Anime', 'Anime Categoria 90');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Tecnologia', 'Tecnologia Categoria 91');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Rol en Vivo', 'Rol en Vivo Categoria 92');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fandom', 'Fandom Categoria 93');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Ilustracion', 'Ilustracion Categoria 94');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Juegos de Mesa', 'Juegos de Mesa Categoria 95');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Manga', 'Manga Categoria 96');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Fantasia', 'Fantasia Categoria 97');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Coleccionismo', 'Coleccionismo Categoria 98');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Ilustracion', 'Ilustracion Categoria 99');
INSERT INTO CATEGORIA (nombre, descripcion) VALUES ('Cine', 'Cine Categoria 100');

-- Eliminar 100 categorías (IDs del 101 al 200)
DELETE FROM CATEGORIA WHERE id_categoria BETWEEN 101 AND 200;

-- Reajustar las claves ajenas en la tabla EVENTO
UPDATE EVENTO
SET id_categoria = id_categoria - 100
WHERE id_categoria > 100;

-- 2. Insertar 200 Eventos
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Concurso de Realidad Virtual', 'Competencia donde los participantes muestran sus habilidades en experiencias inmersivas de realidad virtual.', 'Espacio Talleres #3', '2025-04-13', '2025-04-13', 47);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Juegos de Mesa', 'Reunión para disfrutar de juegos de mesa clásicos y modernos en un ambiente familiar.', 'Sala Principal #1', '2026-12-28', '2026-12-31', 43);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de Merchandising', 'Evento para explorar productos exclusivos y coleccionables de diversas franquicias.', 'Pabellon B #3', '2025-10-04', '2025-10-07', 34);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Doblaje', 'Sesión interactiva con actores de doblaje, donde comparten sus experiencias y técnicas.', 'Salon de Actos #1', '2025-03-13', '2025-03-16', 39);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Presentacion de Cosplay', 'Desfile de cosplay donde los participantes muestran sus trajes inspirados en personajes populares.', 'Area Cosplay #2', '2025-05-13', '2025-05-14', 53);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Panel de Rol en Vivo', 'Discusión sobre técnicas y experiencias en el mundo del rol en vivo.', 'Salon de Actos #4', '2025-09-08', '2025-09-11', 13);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Panel de Tecnologia', 'Exploración de las últimas innovaciones tecnológicas y su impacto en la sociedad.', 'Zona Indie #3', '2026-01-19', '2026-01-21', 44);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Panel de E-Sports', 'Charla sobre el crecimiento de los deportes electrónicos y su futuro.', 'Pabellon B #2', '2026-06-02', '2026-06-05', 89);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Competicion de Fandom', 'Evento donde los fanáticos compiten mostrando su conocimiento y creatividad.', 'Auditorio #5', '2026-06-15', '2026-06-18', 93);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Concurso de Retro', 'Competencia para los amantes de lo retro, desde videojuegos hasta cultura pop.', 'Area Cosplay #1', '2025-10-26', '2025-10-29', 75);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de Coleccionismo', 'Congreso de Coleccionismo 11', 'Salon de Actos #5', '2026-04-15', '2026-04-16', 76);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Taller de Doblaje', 'Taller de Doblaje 12', 'Area Cosplay #3', '2025-12-28', '2025-12-30', 79);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Torneo de Fandom', 'Torneo de Fandom 13', 'Espacio Talleres #5', '2026-02-10', '2026-02-12', 63);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Feria de Cine', 'Feria de Cine 14', 'Sala Conferencias #2', '2026-08-21', '2026-08-21', 66);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Taller de Anime', 'Taller de Anime 15', 'Zona Indie #3', '2026-11-18', '2026-11-20', 56);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Feria de Coleccionismo', 'Feria de Coleccionismo 16', 'Pabellon A #1', '2026-12-19', '2026-12-20', 89);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Demostracion de Cine', 'Demostracion de Cine 17', 'Auditorio #1', '2025-08-01', '2025-08-04', 45);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Torneo de E-Sports', 'Torneo de E-Sports 18', 'Area Cosplay #1', '2025-04-28', '2025-04-28', 93);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Concurso de Coleccionismo', 'Concurso de Coleccionismo 19', 'Escenario Exterior #2', '2026-07-19', '2026-07-20', 95);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Concurso de E-Sports', 'Concurso de E-Sports 20', 'Salon de Actos #5', '2026-04-18', '2026-04-21', 84);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Torneo de Realidad Virtual', 'Torneo de Realidad Virtual 21', 'Pabellon B #4', '2025-07-18', '2025-07-20', 10);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de Guionismo', 'Congreso de Guionismo 22', 'Espacio Talleres #3', '2026-10-17', '2026-10-17', 57);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Presentacion de Retro', 'Presentacion de Retro 23', 'Pabellon B #3', '2025-05-22', '2025-05-23', 91);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de Superheroes', 'Congreso de Superheroes 24', 'Pabellon B #1', '2026-08-21', '2026-08-23', 35);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Feria de Guionismo', 'Feria de Guionismo 25', 'Espacio Talleres #4', '2026-04-04', '2026-04-07', 87);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Feria de Comics', 'Feria de Comics 26', 'Pabellon B #5', '2025-04-15', '2025-04-18', 59);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Presentacion de Tecnologia', 'Presentacion de Tecnologia 27', 'Pabellon B #3', '2025-04-10', '2025-04-11', 23);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Panel de E-Sports', 'Panel de E-Sports 28', 'Auditorio #4', '2026-05-21', '2026-05-22', 68);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Concurso de Superheroes', 'Concurso de Superheroes 29', 'Pabellon A #5', '2025-02-11', '2025-02-11', 94);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Competicion de Doblaje', 'Competicion de Doblaje 30', 'Zona Gaming #3', '2025-12-13', '2025-12-14', 78);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Demostracion de Comics', 'Demostracion de Comics 31', 'Cine Frik #3', '2025-08-10', '2025-08-11', 87);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Presentacion de Cosplay', 'Presentacion de Cosplay 32', 'Pabellon A #4', '2025-02-16', '2025-02-16', 5);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Concurso de Merchandising', 'Concurso de Merchandising 33', 'Salon de Actos #2', '2026-08-24', '2026-08-24', 55);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Juegos de Mesa', 'Encuentro de Juegos de Mesa 34', 'Zona Gaming #5', '2026-07-13', '2026-07-14', 60);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Taller de Fandom', 'Taller de Fandom 35', 'Pabellon B #4', '2025-02-16', '2025-02-18', 93);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de IA', 'Congreso de IA 36', 'Salon de Actos #4', '2025-06-17', '2025-06-17', 49);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de Manga', 'Congreso de Manga 37', 'Pabellon B #1', '2025-12-04', '2025-12-07', 12);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Demostracion de Doblaje', 'Demostracion de Doblaje 38', 'Area Cosplay #1', '2025-03-28', '2025-03-29', 47);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Panel de Anime', 'Panel de Anime 39', 'Zona Indie #4', '2025-11-02', '2025-11-04', 27);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Rol en Vivo', 'Encuentro de Rol en Vivo 40', 'Cine Frik #5', '2026-04-27', '2026-04-29', 40);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Taller de Superheroes', 'Taller de Superheroes 41', 'Pabellon A #5', '2026-03-10', '2026-03-13', 16);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Demostracion de Guionismo', 'Demostracion de Guionismo 42', 'Pabellon B #2', '2026-03-12', '2026-03-12', 31);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Concurso de Realidad Virtual', 'Concurso de Realidad Virtual 43', 'Sala Conferencias #2', '2025-04-23', '2025-04-24', 35);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Presentacion de Doblaje', 'Presentacion de Doblaje 44', 'Salon de Actos #5', '2026-09-29', '2026-09-30', 47);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Torneo de Fandom', 'Torneo de Fandom 45', 'Pabellon A #2', '2026-07-06', '2026-07-08', 65);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Torneo de Tecnologia', 'Torneo de Tecnologia 46', 'Zona Indie #2', '2025-10-17', '2025-10-17', 60);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Panel de Merchandising', 'Panel de Merchandising 47', 'Pabellon B #1', '2025-01-01', '2025-01-01', 35);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Panel de Realidad Virtual', 'Panel de Realidad Virtual 48', 'Espacio Talleres #2', '2025-07-24', '2025-07-26', 89);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Ciencia Ficcion', 'Encuentro de Ciencia Ficcion 49', 'Cine Frik #3', '2025-03-29', '2025-03-31', 57);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Competicion de Fandom', 'Competicion de Fandom 50', 'Sala Principal #2', '2026-03-14', '2026-03-15', 44);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Feria de Fandom', 'Feria de Fandom 51', 'Sala Conferencias #1', '2026-07-27', '2026-07-28', 90);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Series', 'Encuentro de Series 52', 'Auditorio #3', '2025-08-18', '2025-08-18', 35);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Concurso de IA', 'Concurso de IA 53', 'Pabellon B #5', '2025-05-14', '2025-05-17', 17);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Feria de Anime', 'Feria de Anime 54', 'Pabellon A #1', '2025-08-26', '2025-08-29', 73);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de E-Sports', 'Congreso de E-Sports 55', 'Salon de Actos #5', '2026-08-20', '2026-08-22', 36);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Torneo de Comics', 'Torneo de Comics 56', 'Pabellon B #5', '2025-03-28', '2025-03-29', 94);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Concurso de Manga', 'Concurso de Manga 57', 'Area Cosplay #1', '2026-08-06', '2026-08-08', 69);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Merchandising', 'Encuentro de Merchandising 58', 'Pabellon A #5', '2025-09-26', '2025-09-26', 16);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Demostracion de Superheroes', 'Demostracion de Superheroes 59', 'Zona Gaming #3', '2025-08-04', '2025-08-07', 74);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Competicion de Coleccionismo', 'Competicion de Coleccionismo 60', 'Zona Gaming #2', '2025-02-07', '2025-02-09', 35);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Competicion de Doblaje', 'Competicion de Doblaje 61', 'Pabellon B #2', '2026-06-16', '2026-06-18', 6);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Concurso de Cine', 'Concurso de Cine 62', 'Auditorio #4', '2026-10-24', '2026-10-27', 42);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Competicion de Doblaje', 'Competicion de Doblaje 63', 'Pabellon B #5', '2025-12-22', '2025-12-25', 37);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Proyeccion de Fantasia', 'Proyeccion de Fantasia 64', 'Pabellon B #1', '2026-07-22', '2026-07-23', 82);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Taller de Cine', 'Taller de Cine 65', 'Auditorio #1', '2025-11-29', '2025-11-30', 33);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Panel de Doblaje', 'Panel de Doblaje 66', 'Pabellon A #2', '2026-05-27', '2026-05-27', 62);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Feria de Guionismo', 'Feria de Guionismo 67', 'Salon de Actos #4', '2025-06-05', '2025-06-06', 61);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de Anime', 'Congreso de Anime 68', 'Salon de Actos #4', '2026-03-28', '2026-03-28', 94);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Charla de Comics', 'Charla de Comics 69', 'Area Cosplay #3', '2025-10-11', '2025-10-12', 15);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Torneo de Fantasia', 'Torneo de Fantasia 70', 'Salon de Actos #3', '2025-03-04', '2025-03-06', 29);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Presentacion de Guionismo', 'Presentacion de Guionismo 71', 'Pabellon A #3', '2026-06-25', '2026-06-25', 92);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Demostracion de E-Sports', 'Demostracion de E-Sports 72', 'Pabellon B #1', '2026-08-27', '2026-08-27', 83);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Guionismo', 'Encuentro de Guionismo 73', 'Salon de Actos #4', '2026-02-06', '2026-02-08', 10);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Charla de Guionismo', 'Charla de Guionismo 74', 'Pabellon B #3', '2026-04-14', '2026-04-17', 18);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Competicion de IA', 'Competicion de IA 75', 'Salon de Actos #3', '2026-04-25', '2026-04-25', 82);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Feria de Retro', 'Feria de Retro 76', 'Sala Conferencias #5', '2025-05-18', '2025-05-19', 80);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Proyeccion de Coleccionismo', 'Proyeccion de Coleccionismo 77', 'Pabellon B #1', '2025-10-20', '2025-10-22', 89);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Proyeccion de Coleccionismo', 'Proyeccion de Coleccionismo 78', 'Sala Conferencias #1', '2025-10-06', '2025-10-07', 96);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de Rol en Vivo', 'Congreso de Rol en Vivo 79', 'Salon de Actos #2', '2025-07-22', '2025-07-25', 74);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Feria de Merchandising', 'Feria de Merchandising 80', 'Cine Frik #2', '2025-10-26', '2025-10-28', 10);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Demostracion de Coleccionismo', 'Demostracion de Coleccionismo 81', 'Area Cosplay #1', '2025-01-16', '2025-01-17', 51);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Presentacion de Anime', 'Presentacion de Anime 82', 'Salon de Actos #2', '2025-07-12', '2025-07-14', 75);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Proyeccion de Realidad Virtual', 'Proyeccion de Realidad Virtual 83', 'Sala Principal #5', '2026-05-09', '2026-05-10', 14);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Charla de Realidad Virtual', 'Charla de Realidad Virtual 84', 'Sala Conferencias #1', '2025-02-08', '2025-02-11', 94);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de Ciencia Ficcion', 'Congreso de Ciencia Ficcion 85', 'Cine Frik #5', '2026-05-24', '2026-05-24', 18);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Fantasia', 'Encuentro de Fantasia 86', 'Zona Gaming #1', '2025-07-19', '2025-07-21', 40);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Charla de Realidad Virtual', 'Charla de Realidad Virtual 87', 'Pabellon B #1', '2026-10-22', '2026-10-23', 12);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Presentacion de Coleccionismo', 'Presentacion de Coleccionismo 88', 'Auditorio #4', '2026-08-05', '2026-08-05', 35);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de Retro', 'Congreso de Retro 89', 'Area Cosplay #4', '2026-01-14', '2026-01-16', 90);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Panel de Ciencia Ficcion', 'Panel de Ciencia Ficcion 90', 'Pabellon A #2', '2025-08-13', '2025-08-16', 68);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Doblaje', 'Encuentro de Doblaje 91', 'Pabellon B #2', '2025-03-16', '2025-03-16', 57);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Cultura Pop', 'Encuentro de Cultura Pop 92', 'Auditorio #3', '2025-11-03', '2025-11-04', 90);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de Cultura Pop', 'Congreso de Cultura Pop 93', 'Zona Gaming #5', '2026-08-04', '2026-08-05', 11);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Taller de Doblaje', 'Taller de Doblaje 94', 'Area Cosplay #4', '2025-05-10', '2025-05-13', 95);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Concurso de Superheroes', 'Concurso de Superheroes 95', 'Zona Indie #3', '2025-07-19', '2025-07-22', 64);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Presentacion de E-Sports', 'Presentacion de E-Sports 96', 'Sala Principal #1', '2025-03-24', '2025-03-27', 86);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Congreso de IA', 'Congreso de IA 97', 'Pabellon B #4', '2026-08-19', '2026-08-19', 15);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Feria de Ciencia Ficcion', 'Feria de Ciencia Ficcion 98', 'Zona Indie #1', '2025-06-15', '2025-06-15', 14);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Taller de Cultura Pop', 'Taller de Cultura Pop 99', 'Zona Indie #1', '2025-07-26', '2025-07-29', 75);
INSERT INTO EVENTO (nombre, descripcion, lugar, fecha_inicio, fecha_fin, id_categoria) VALUES ('Encuentro de Fandom', 'Encuentro de Fandom 100', 'Auditorio #3', '2025-11-02', '2025-11-04', 80);

-- Eliminar 100 eventos (IDs del 101 al 200)
DELETE FROM EVENTO WHERE id_evento BETWEEN 101 AND 200;

-- Reajustar las claves primarias de EVENTO (opcional, si es necesario)
-- ALTER TABLE EVENTO AUTO_INCREMENT = 101;

-- Nota: Asegúrate de que las claves primarias y foráneas estén correctamente configuradas en la base de datos.

